// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCqF5pklh6a7HYBv7T92aMy5g41hEqrM',
    appId: '1:160226992403:web:e50aaf5484408217a97ae6',
    messagingSenderId: '160226992403',
    projectId: 'palsap-61cb2',
    authDomain: 'palsap-61cb2.firebaseapp.com',
    storageBucket: 'palsap-61cb2.appspot.com',
    measurementId: 'G-CY75LG74SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBezeJgsc9CTcd70VjRzTap_cas880YgGE',
    appId: '1:160226992403:android:08ab3561b20cdf46a97ae6',
    messagingSenderId: '160226992403',
    projectId: 'palsap-61cb2',
    storageBucket: 'palsap-61cb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVS1-dIursMmQl0zB6ECNos6Qkyqqg8I',
    appId: '1:160226992403:ios:6324d38cf9ebeb9aa97ae6',
    messagingSenderId: '160226992403',
    projectId: 'palsap-61cb2',
    storageBucket: 'palsap-61cb2.appspot.com',
    iosBundleId: 'com.example.ACM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVS1-dIursMmQl0zB6ECNos6Qkyqqg8I',
    appId: '1:160226992403:ios:1f102b89de0adbb9a97ae6',
    messagingSenderId: '160226992403',
    projectId: 'palsap-61cb2',
    storageBucket: 'palsap-61cb2.appspot.com',
    iosBundleId: 'com.example.ACM.RunnerTests',
  );
}